### ISSUE TITLE
Support for the XDG Base Directories Specification

### ISSUE THREAD

**Issue by 0x5c** [gwsw/less#153]
Less only looks for/creates the history in the home directory, contributing to the clutter there. Overriding this requires of the user the addition of `~/lesskey`, which also contributes to clutter, or the addition of an environment variable (which is not nice when the problem is cluttering-by-default, see [this background on "dotfiles"](https://archive.is/vfXl2), [this patchwork attempt](https://lewiscowper.com/post/dotcrap/), and [this one](https://github.com/hauleth/xdg-rlz)).

On Linux, the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is a well established de-facto standard on where to place "dotfiles". It defines multiple environment variables, and the defaults they should have.

For less, `$XDG_DATA_HOME` and `$XDG_CONFIG_HOME` are the directories of interest.
When unspecified, those are to default to `$HOME/.local/share/` and `$HOME/.config`, respectively.
`.lesskey` would go in `$XDG_CONFIG_HOME/less/lesskey` since it's a configuration file
`.lesshst` would go in `$XDG_DATA_HOME/less/lesshst` since it's local data

To avoid breaking any existing less installation, I suggest searching for the files at their current default location before searching in the XDG locations. The default location for creation of a new `lesshst` file should be in `$XDG_DATA_HOME`.

**Comment by gwsw** [comment]
So I think the logic you're requesting would look like this.

For .lesshst:
```
if $LESSHISTFILE is set
  use $LESSHISTFILE
else if $XDG_DATA_HOME is set and $HOME/.lesshst does not exist
  use $XDG_DATA_HOME/.lesshst
else
  use $HOME/.less
```
and for .less:
```
if $LESSKEY is set
  use $LESSKEY
else if $XDG_CONFIG_HOME is set and $HOME/.less does not exist
  use $XDG_CONFIG_HOME/.less
else
  use $HOME/.less
```
and a similar logic for .lesskey.

Although it's not quite as simple as that because different systems use different logic. It's $HOME/.file in Linux but in Windows and MS-DOS it's the result of searchpath(), and in OS/2 it's either $INIT/.file or the result of _searchenv(), so the middle clause would be "$XDG_xxx_HOME is set and the file can't be found anywhere" on these systems. 

I guess this would be ok although I dislike complicating this logic to the point where the user can't easily predict where the files will be.

**Comment by eli-schwartz** [comment]
> Although it's not quite as simple as that because different systems use different logic. It's $HOME/.file in Linux but in Windows and MS-DOS it's the result of searchpath(), and in OS/2 it's either $INIT/.file or the result of _searchenv(), so the middle clause would be "$XDG_xxx_HOME is set and the file can't be found anywhere" on these systems.

Operating Systems have platform conventions which should generally be followed (XDG is just the freedesktop one shared by freedesktop-respecting Unixes):

- [the Windows one](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid?redirectedfrom=MSDN) is *supposed* to be simple: `%AppData%\Roaming`. As with XDG, it obviously makes sense to continue to respect the location from older versions of the program (has it so far iterated over the entire path?)
- [macOS](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6) prefers `~/Library/Application Support/`


It's probably safe to check the new location first, since both old/new locations should probably not simultaneously exist.

**Comment by gwsw** [comment]
But $LESSHISTFILE and $LESSKEY must override any generic rules for data file locations based on $XDG_* or anything else, since those are settings that specifically apply to less.

**Comment by 0x5c** [comment]
> So I think the logic you're requesting would look like this.
> 
> For .lesshst:
> 
> ```
> if $LESSHISTFILE is set
>   use $LESSHISTFILE
> else if $XDG_DATA_HOME is set and $HOME/.lesshst does not exist
>   use $XDG_DATA_HOME/.lesshst
> else
>   use $HOME/.less
> ```
> 
> and for .less:
> 
> ```
> if $LESSKEY is set
>   use $LESSKEY
> else if $XDG_CONFIG_HOME is set and $HOME/.less does not exist
>   use $XDG_CONFIG_HOME/.less
> else
>   use $HOME/.less
> ```
> 
> and a similar logic for .lesskey.

As-far is linux (distros not following XDG are rare) goes (and the unixes that follow XDG), the spec requires a compliant fallback default of `$HOME/.config` and `$HOME/.local/share`. But only complying when the XDG HOME variables are defined is a common compromise and works out-of-the-box on some common distros.
But since the spec defines a common default fallback, distros tend to not set those variables unless they use custom locations.

Just to clarify, the XDG dirs would be used by less as base paths to be appended by a directory called `less` (without dot):
- `$XDG_CONFIG_HOME/less/` would contain `lesskey` and/or any other config file
- `$XDG_DATA_HOME/less/` would contain `lesshst` and/or any other local data file

It's important to not have a `.less` directory with config+data in any of those.


> Although it's not quite as simple as that because different systems use different logic. It's $HOME/.file in Linux but in Windows and MS-DOS it's the result of searchpath(), and in OS/2 it's either $INIT/.file or the result of _searchenv(), so the middle clause would be "$XDG_xxx_HOME is set and the file can't be found anywhere" on these systems.
> 
> I guess this would be ok although I dislike complicating this logic to the point where the user can't easily predict where the files will be.

Yes, it's OS-specific logic, and the XDG dirs should not be followed for Windows (although some programs do). There's debate on whether it should apply on MacOS (Apple has their own spec), and it's unclear which of the Unixes follows the XDG dirs spec.
It's OS-specific logic, but users have OS-specific expectations; most linux users who actually do create custom configuration for their tools generally expect the configuration and data to go specific locations that are defined by the OS. Dotfiles managers on linux also generally expect those locations to be respected.
The users that aren't "[distro] users" but "less users" who expect the config to be directly inside their home directory.

Having XDG compliance be a compile-time flag would ensure that package maintainers for XDG-compliant OSes can enable it.
That would also avoid needing to go with the compromise mentioned earlier.

------

> But $LESSHISTFILE and $LESSKEY must override any generic rules for data file locations based on $XDG_* or anything else, since those are settings that specifically apply to less.

Indeed, the XDG dirs spec *must not* override those existing mechanisms.

**Comment by eli-schwartz** [comment]
> But $LESSHISTFILE and $LESSKEY must override any generic rules for data file locations based on $XDG_* or anything else, since those are settings that specifically apply to less.

Of course. Lots of programs come with program-specific "FOO_CONFIG_DIR" style environment variables too, and in such cases the program must completely skip checking for anything else.

> Yes, it's OS-specific logic, and the XDG dirs should not be followed for Windows (although some programs do). There's debate on whether it should apply on MacOS (Apple has their own spec), and it's unclear which of the Unixes follows the XDG dirs spec.

Some people debate that Apple's spec is intended only for GUI programs, not CLI tools. I'm not a macOS user and have no opinion on this viewpoint. But common utility libraries for querying "the current OS standard directory" (appdirs.py, QStandardPaths, dirs-rs, etc.) follow Apple's spec for CLI programs too.

"The Unixes" spoken of don't have OS-level functions like the Windows `Knownfolders.h` constants, or macOS baking constant directory names into Finder to hide them by default and proxying `~/Library/Preferences` through `NSUserDefaults` / `CFPreferences` and stuff. The common convention is to treat the *BSDs like freedesktop, just like it is "common convention" to treat Linux like freedesktop despite there being no "linux authority" to mandate it.

**Comment by gwsw** [comment]
>Just to clarify, the XDG dirs would be used by less as base paths to be appended by a directory called less (without dot):

Hm, so less needs to create the directory if it doesn't exist? In fact, it needs to create all the directories in the path that don't currently exist? That's unfortunate.

**Comment by eli-schwartz** [comment]
XDG specifies that information should be stored within the configuration or data root location.

Some people interpret that to mean "use the file ~/.config/lesskey", and some people interpret that to mean "arbitrarily extend the XDG standard to make some unrelated, pedantic point about reserving an entire directory for your application in case you need to create more files and don't want to create multiple top-level files, therefore use ~/.config/less/lesskey".

Random opinionated subjective claim: the latter people are wrong, use of ~/.config/lesskey is my holy article of faith and moral rectitude.

Okay, pushy personal opinions aside... objectively, the people arguing for a directory would also say you "need" to use ~/.less/lesskey for the non-XDG version of the lookup, and on that logic, the software has been "wrong" for many many years since before XDG was invented.

There is an interesting discussion to have here, even if I personally disagree, but one thing I'll definitely insist on is that "use a less/ directory" is outside the scope of this ticket, which only requests to migrate from $HOME to $XDG_CONFIG_HOME (and drop a redundant dot prefix since it's no longer being used to trigger "hidden files" mode).

@0x5c Please open a new ticket to separately discuss `less/`.

@gwsw assuming the history file is in $XDG_DATA_HOME/.lesshst with no additional directory, this containing directory will *probably* exist already, since many things create it, and there are worse fates for users to suffer than to have it fall back on $HOME if that directory does not exist. But, assuming anything other than $HOME is used, you *might* end up needing that directory created first (maybe less is one of the first programs a new user runs?) so if it's easy to do, then "why not"? Up to you.

... Random thought: what happens if a user specifies a $LESSHISTFILE in a non-existent directory? Does the directory get created so the file can be written? I haven't checked.

**Comment by 0x5c** [comment]
> >Just to clarify, the XDG dirs would be used by less as base paths to be appended by a directory called less (without dot):
> 
> Hm, so less needs to create the directory if it doesn't exist? In fact, it needs to create all the directories in the path that don't currently exist? That's unfortunate.

Yes, since this is the convention used on such systems

**Comment by 0x5c** [comment]
> XDG specifies that information should be stored within the configuration or data root location.
> 
> Some people interpret that to mean "use the file ~/.config/lesskey", and some people interpret that to mean "arbitrarily extend the XDG standard to make some unrelated, pedantic point about reserving an entire directory for your application in case you need to create more files and don't want to create multiple top-level files, therefore use ~/.config/less/lesskey".
> 
> Random opinionated subjective claim: the latter people are wrong, use of ~/.config/lesskey is my holy article of faith and moral rectitude.
> 
> Okay, pushy personal opinions aside... objectively, the people arguing for a directory would also say you "need" to use ~/.less/lesskey for the non-XDG version of the lookup, and on that logic, the software has been "wrong" for many many years since before XDG was invented.
> 
> There is an interesting discussion to have here, even if I personally disagree, but one thing I'll definitely insist on is that "use a less/ directory" is outside the scope of this ticket, which only requests to migrate from $HOME to $XDG_CONFIG_HOME (and drop a redundant dot prefix since it's no longer being used to trigger "hidden files" mode).

No programs break the spec, and there's no need to create one.


> @0x5c Please open a new ticket to separately discuss `less/`.

I made this feature request as-is, and that's how it is.
You are free to comment with your opinion here. There is no need to create more tickets.

**Comment by 0x5c** [comment]
As for how to handle directory creation, this is what the spec says

> If, when attempting to write a file, the destination directory is non-existant an attempt should be made to create it with permission 0700. If the destination directory exists already the permissions should not be changed. The application should be prepared to handle the case where the file could not be written, either because the directory was non-existant and could not be created, or for any other reason. In such case it may chose to present an error message to the user.

**Comment by eli-schwartz** [comment]
> No programs break the spec, and there's no need to create one.

Correct, because the spec does NOT say a directory must be used.

In many applications, it makes sense to use an application directory containing multiple files worth of configuration.
In many applications, it does not make sense to use an application directory containing exactly one file worth of configuration, no more, no less.

I do have multiple programs storing configuration files directly in $XDG_CONFIG_HOME/, for example the official XDG software "xdg-user-dirs" uses the configuration files `$XDG_CONFIG_HOME/user-dirs.dirs` and `$XDG_CONFIG_HOME/user-dirs.locale`.

Are you going to argue that the officially blessed XDG software is violating the XDG spec?

**Comment by 0x5c** [comment]
> for example the official XDG software "xdg-user-dirs" uses the configuration files $XDG_CONFIG_HOME/user-dirs.dirs and $XDG_CONFIG_HOME/user-dirs.locale.

That peculiar


Regardless, since the data home directory will have to be created for the history if not present, so might as well create `less/`.



------

As it currently is, how does less deals with an unset `$HOME`? Is history creation still attempted? What is done when the directory in that variable is non existent, and when its not writable? 

On a slight tangent, this file/directory creation business (and the logic behind it) could be rendered moot if saving history was not the default; "history is only saved if you specify where".
Then less would only have to implement a lookup order for the config file, where support for XDG dirs would be trivial to achieve. 
*I am in no way asking for this*, but that's an option I thought of.

**Comment by gwsw** [comment]
less currently never creates directories. It doesn't call mkdir nor does the configure script check for its existence, the Windows build doesn't call CreateDirectory, the OS/9 build doesn't call whatever API creates directories there, etc. If $HOME doesn't exist (or is not writable), it will just not write a history file.

**Comment by gwsw** [comment]
>  (and drop a redundant dot prefix since it's no longer being used to trigger "hidden files" mode).

Is there anything wrong with retaining the dot? It's a little easier to use the same basename whether it's stored in $HOME or $XDG_DATA_HOME.

**Comment by eli-schwartz** [comment]
The dot is just cosmetics, the redundancy might look odd but the standard doesn't exactly voice an opinion on the subject.
(Maybe because it doesn't specify "how to simplify the code which handles backwards compat with pre-XDG filenames. ;))

I would prefer no dot. But it's also not my code and I haven't even offered a patch which implements this ticket, so I will gratefully accept whichever change lets me drop a bashrc environment variable and use a ~/.config file to hold options instead.

(I would personally go for slightly more code to make end user functionality a little bit prettier. I think it would be the only file I'd have in XDG_CONFIG_HOME with a redundant dot in the name.)

**Comment by 0x5c** [comment]
> > (and drop a redundant dot prefix since it's no longer being used to trigger "hidden files" mode).
> 
> Is there anything wrong with retaining the dot? It's a little easier to use the same basename whether it's stored in $HOME or $XDG_DATA_HOME.

The earlier complaint of "the user can't easily predict where the files will be" only becomes true on XDG systems if you use bare files or directories with dots, use no subdirectories (to a lesser extent), or disregard platform-specific expectations like less currently does.
To demonstrate the first case, I've created `.lesshst` and `.less/.lesshst` in my `$XDG_DATA_HOME`, and listed the files within:
```none
$ ls .local/share
chezmoi  mc  nano
```
Both the mock history file and the directory fail to show when listing the directory in a normal manner, while other programs that save data make themselves known instantly.

------

The second case applies when the user wants to know "what information does `less` save?". 
To demonstrate that one, `lesshst` was created directly in `$XDG_DATA_HOME`, and the contents of `$XDG_DATA_HOME/less` listed:
```none
$ ls .local/share/less
ls: cannot access '.local/share/less': No such file or directory
```
"ah, it saves nothing", since there's nothing where it's expected. The existence of the history file would only be revealed by either listing the contents of the data home, or by reading the manual page (which a user would probably read were the question important to them).
While this second case is much less important and probable, it remains something to consider.

**Comment by gwsw** [comment]
Well, I think almost every CLI user knows how dot files work and won't be surprised that ls without -a doesn't show them. My concern was about the user being able to predict where the datafiles are saved without looking for them. Your examples show something slightly different, the ease of finding files that are already there. I'm afraid that your line of reasoning would suggest that I shouldn't make this change at all, since currently the files are in only one place ($HOME), while after this change they may be in either $HOME or $XDG_DATA_HOME depending on the history of the system (which versions of less have been run previously). Going forward everyone will need to remember that files may be in one of at least two places. I think that's a degradation in ease of use, but I'm prepared to accept it.

I have the feature mostly coded and am testing it. I will drop the dots from the names in the XDG directories. I'm inclined to put lesshst directly in XDG_DATA_HOME and lesskey directly in XDG_CONFIG_HOME.

**Comment by eli-schwartz** [comment]
> The second case applies when the user wants to know "what information does less save?".

If users don't want to look in the manual page to see the well-written, definitive documentation on the subject, then they will need to guess whether the program uses a file or a directory, and they will also need to guess whether it is using a "company name" rather than the executable command name, and whether any of it is capitalized, and a number of other quirks.

Because a common convention for storing XDG_CONFIG_HOME or XDF_DATA_HOME files is "Company Name/progname/prog.conf", which is a whole lot of indirection, but proponents of the style say that it allows you to install and use multiple projects all named "less".

The same people would recommend renaming /usr/bin/less to /usr/bin/com.github.gwsw.less to allow other projects to also call themselves "less".

I'm personally not interested in so many layers. I just want to track my dotfiles in .config instead of $HOME. Using $HOME/.config/lesskey thus makes me happy.

**Comment by 0x5c** [comment]
> Well, I think almost every CLI user knows how dot files work and won't be surprised that ls without -a doesn't show them.

XDG homes are in-part there to undo that `-a` requirement, since nothing would justify the goal of hiding files if they're already not cluttering day-to-day directories. 

> My concern was about the user being able to predict where the datafiles are saved without looking for them.

This suggests that saving the history file should not be the default, since the user can't expect history to be saved without looking for an history file in the first place.
In my opinion the history file is not a problem if it follows platform-specific expectation, and you said that you have a patch almost ready for that so I don't see a any problem with the history file continuing to exist.

> Your examples show something slightly different, the ease of finding files that are already there. I'm afraid that your line of reasoning would suggest that I shouldn't make this change at all, since currently the files are in only one place ($HOME), while after this change they may be in either $HOME or $XDG_DATA_HOME depending on the history of the system (which versions of less have been run previously). Going forward everyone will need to remember that files may be in one of at least two places. I think that's a degradation in ease of use, but I'm prepared to accept it.

This is why platform-specific expectations are critical to consider;
Users of XDG-compliant distros/OSes expect tools to follow that spec. They won't expect that *any* given tool would break that spec.
This breaking of the spec *is* that ease of use degradation.
Additional user-specific preferences are just that, user-specific preferences, and using less' environment variables to enforce them is an adequate solution.

> I have the feature mostly coded and am testing it. I will drop the dots from the names in the XDG directories. I'm inclined to put lesshst directly in XDG_DATA_HOME and lesskey directly in XDG_CONFIG_HOME.

Not a perfect solution, but much better than the current behaviour and greatly appreciated.
Thanks :)

**Comment by gwsw** [comment]
Implemented in v583 (e3af3f5f15aee14bffc3afa062d7647ce7f09cc4).
Let me know it doesn't act as expected.

**Comment by rashil2000** [comment]
Thank you :)

**Comment by oliv3r** [comment]
@gwsw and @0x5c

Why was $XDG_DATA_HOME chosen for the history file? The more accurate location is actually $XDG_STATE_HOME, where generally history files (state-based files) are put. For a decent overview see https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by eli-schwartz** [comment]
I suppose because back in April, there was no such thing.

This ticket was implemented on April 27
XDG_STATE_HOME was released in the basedir spec version 0.8 on May 08.

**Comment by 0x5c** [comment]
XDG_STATE_HOME was not yet part of the standard, and wasn't in widespread use either. I personally did not even hear about it before seeing the news covering the recent standardisation of it, despite having read countless documents, blogs, articles, and whatnot about xdg base dirs

**Comment by oliv3r** [comment]
Thank you for your answer @eli-schwartz and @0x5c; that was fair enough. :) I've created #223 to address this.
