### ISSUE TITLE
-FcX interaction

### ISSUE THREAD

**Issue by adoxa** [gwsw/less#173]
I've always had `-c` set in the `LESS` variable. Using `-F` with that will cause all the tildes to display. I've currently fixed that by adding:

```
if (!(quit_if_one_screen && one_screen))
...
else
	top_scroll = 0;
```

However, that then fails with `-X`, since it doesn't set `one_screen`. Without `-c` (and `-F`) there are no tildes at all, the prompt is displayed directly after the file (Windows). They're restored with a second file, though (i.e. the first file has none, the second has them, and going back to the first they're still there).

Not a big deal, since I rarely use `-F`, just wanted to make it known.

**Comment by gwsw** [comment]
This behavior (screen filled with tildes) seems to me to be inherent in the meaning of the -c flag. The -c flag tells less to start painting from the top line of the screen. In doing so, it abandons the ability to have the screen in "squished" mode, where less than a screenful of text is at the bottom of the screen. Let me know if I'm not understanding something.

**Comment by adoxa** [comment]
It's just not what I was expecting when I used `-F`. If you don't think `-F` should override `-c` so be it.

**Comment by gwsw** [comment]
It seems to me that there are clear semantics to all four cases of -c and -F being set or unset, so I'm not thrilled about eliminating one of them. It's conceivable that someone would want the current "```-F -c```" behavior. I think the solution should be "don't set -c" if you don't want that behavior. Since you have -c in your LESS, you could use "```-F -+c```" instead of "```-F```", although that's obviously more to type.

**Comment by adoxa** [comment]
Fair enough. In Windows at least, `-F` with `-c` erases the currently displayed window, then scrolls so you lose the first line (with `CMD`; Powershell doesn't have the extra newline). I'll still keep the change for my release.
