### ISSUE TITLE
Output from filter using `LESSOPEN="||..."` is not properly ignored when the filter fails

### ISSUE THREAD

**Issue by abbeyj** [gwsw/less#186]
The man page says:
```
To avoid this, if LESSOPEN starts with two vertical bars, the exit status of the script becomes meaningful.
...
If the exit status is nonzero, any output is ignored and the original file is used.
```

This is not actually happening.  For a filter that both produces output and returns a nonzero exit status the output is not ignored and the original file is not used.  It appears that `less` is only examining the exit status when there is no output.

STR:
```
echo Hello > hello.txt
cat > fail.sh << EOF
#!/bin/sh
echo "This output is from fail.sh"
exit 1
EOF
chmod +x fail.sh
LESSOPEN="||$PWD/fail.sh %s" less hello.txt
```

Actual results:
The text "This output is from fail.sh" is displayed.

Expected results:
The text "Hello" is displayed.

**Comment by gwsw** [comment]
The description in the man page is indeed incorrect. I have changed the man page to correctly describe the current behavior. Changing the code to match the man page runs the risk of breaking compatibility with existing LESSOPEN scripts, and also isn't really feasible because less would need to wait until the script has produced all its output and exited before it could display anything.
