### ISSUE TITLE
Req: Key binding: Shift+Space as PageUp / back-screen

### ISSUE THREAD

**Issue by Jonta** [gwsw/less#217]
Rationale
- Shift+Space is already PgUp in other programs, e.g. Firefox
- Shift modifying/reversing a command is a common convention
- Shift+Space isn't bound to anything else in `less` (551 in my case)
- Shift+Space is a comfortable shortcut to use

Difficulties
- Discussed in https://unix.stackexchange.com/questions/88579/shift-space-in-less
- Where [andrew](https://unix.stackexchange.com/users/27685/andrew) says "less does not currently support this, but it definitely could be added"

If not
- Perhaps andrew is wrong
- Perhaps this should be changed with `lesskey` instead (If so: How? I didn't find a way to use a shift key in `man lesskey`)
- Perhaps this feature is not going to be implemented. If so, we would know to turn to one of the solutions mentioned in the thread above. =)

**Comment by gwsw** [comment]
To be more specific, to implement the xterm-specific change, you would
1. Append ```\e[>4;2m``` to the smcup string in your terminfo.
2. Append ```\e[>m``` to the rmcup string in your terminfo.
3. Add the line ```\e[27;2;32~ back-screen``` to your lesskey file.

Note that due to an unrelated bug, this won't work on versions less-594 and less-595, neither of which were released.
