### ISSUE TITLE
"Cannot use lesskey source file"

### ISSUE THREAD

**Issue by mhwombat** [gwsw/less#219]
When I try to use a lesskey source file, I get the following error.

```
$ less --lesskey-src=~/dotWombat/.config/lesskey ~/dotWombat/.config/kitty/kitty.conf
Cannot use lesskey source file "~/dotWombat/.config/lesskey"
Press RETURN to continue
```

Here's the version of less:
```
$ less --version
less 590 (POSIX regular expressions)
Copyright (C) 1984-2021  Mark Nudelman
```

Here's the source file. It doesn't have much at the moment, but my ultimate goal is to alter some key bindings (once I get past this issue).

```
$ cat ~/dotWombat/.config/lesskey                                                   
#command


#line-edit


#env
LESS=-R
```

Relevant environment variables:

```
$ env | grep -i less                                                                           
LESSHISTFILE=/history
LESSOPEN=|/nix/store/b8xf3i0kdfz7is8w9sf4jf5jg4ywxxa9-lesspipe-1.85/bin/lesspipe.sh %s
PAGER=less
LESSKEYIN_SYSTEM=/nix/store/pslwcgd0l9q4xr98klp2lr66296bvxs6-lessconfig
```

**Comment by gwsw** [comment]
I assume you are using bash as your shell. I think your problem is that bash only expands a tilde when it is the first character of a word. In your example the tilde appears in the middle of the word after the equal sign. You can either replace the equal sign with a space to make the tilde be first in the word, or type the expanded path name of your home directory.

**Comment by mhwombat** [comment]
I'm using zsh, but that was indeed the problem. Thank you!
