### ISSUE TITLE
Less behaves "weird" when used with ansible-vault

### ISSUE THREAD

**Issue by Nudin** [gwsw/less#220]
[I'm not sure if this is an issue in less, ansible or something else. I first posted it [on so](https://stackoverflow.com/questions/69854330/less-behaves-weird-when-used-with-ansible-vault), but didn't get an answer.]

Due to my setup (including gitattributes & git hooks), the output of `ansible-vault view` is piped into less to be seen by me. But in these cases less behaves "weird". It seems like the terminal settings are miss-configured? Pressing 'Return' results in the line (end) to be printed multiple times, the Arrow-Keys result in Keycodes being printed, and shortcuts don't work.

![screen](https://user-images.githubusercontent.com/509205/140922426-6b0d1bf0-7266-4f96-a1e3-1fb1d99e9224.png)

What I tried to pinpoint it down:

-   Piping it through `cat` or `tee`: `ansible-vault view file | tee tmp | less` – the broken behavior occurs
-   Using the tmp-file created by above's `tee`: `cat tmp | less – normal behavior`
-   Comparing and changing environment variables: PAGER, LESSOPEN, LESS_OPTS, SHLVL … – no difference
-   Open less in subshell – still broken
-   Other pagers like 'most' don't show any problems
-   Problem occurs in different terminals (xterm and kitty) and shells (bash and zsh)

**Comment by gwsw** [comment]
I don't know anything about ansible, but the fact that the problem happens when you run ansible-vault, but does not happen when you pipe the exact same file into less without ansible-vault running, makes me think that ansible-vault is manipulating the terminal modes and interfering with less's manipulation of the terminal modes. The behavior seems consistent with the terminal not being correctly set in raw mode with the terminal init string sent. Perhaps ansible-vault is changing terminal modes to turn off echo when a password is input, or something like that?
