### ISSUE TITLE
Infinite loop in the help

### ISSUE THREAD

**Issue by robert-ross** [gwsw/less#235]
Run `less --lesskey-src=./foo ./foo` where
```
$ cat foo
b set-mark bg
```
Pressing "b" works correctly but pressing "h" and then "b" results in an infinite loop.  It is okay for `set-mark` to be ignored in help mode, but then its following letter should also be ignored.

**Comment by gwsw** [comment]
Fixed in f0eb3ee233ef88b224895e292b053441b8a067b1.

**Comment by avih** [comment]
> Fixed in [f0eb3ee](https://github.com/gwsw/less/commit/f0eb3ee233ef88b224895e292b053441b8a067b1).

Are you marking as fixed by commits which don't yet exist on the master branch? Does that mean that post659 branch is to be taken as is into master at some stage? what about 22ac9f0d which I prefer not to be taken yet?

Note except for resetting the master branch to post659, any other import, selective or not, would resule in new commit hashes for the additional commits.

**Comment by gwsw** [comment]
I'm not "marking it fixed" in the sense that I'm closing this issue. It will remain open until this fix is merged into the main branch. I'm just noting that I don't intend to do any more work on this issue except for merging it.

**Comment by avih** [comment]
> so I don't intend to ever merge [22ac9f0](https://github.com/gwsw/less/commit/22ac9f0d1dfc9163a2ca94da19265d23dd96d79f) to the main branch. I'll wait for your later changes.

Thanks.

This means that the commit hash f0eb3ee2 would dissappear after you merge it to master and delete the post659 branch (it would have a different hash at the master branch). That's what I meant.
