### ISSUE TITLE
Follow mode in combination with fifo pipe results in unexpected behavior

### ISSUE THREAD

**Issue by ton** [gwsw/less#244]
I've read in various places how `less +F` can be used as a improvement over `tail -f`. Today I had the following use case that does not seem to work as expected, and I'm pretty sure I've used it in the past where it did work:

```
mkfifo less-pipe
less +F -f less-pipe
```

Then in some other terminal:

```
echo foo > less-pipe
echo bar > less-pipe
```

After echo'ing "foo" to the pipe, less will print `END` and no longer show data coming in over the pipe (I remember in the past seeing `Waiting for more data...`). So it seems follow mode is not active at all. Is this a bug or expected behavior?

I'm using `less` version 590.

**Comment by ton** [comment]
I found that at least version 552 shows the correct behaviour, I'm bisecting this now.

**Comment by ton** [comment]
The following commit introduces my perceived issue: df1494f4825857bb3db1b025f16ecefe4265d6dc

**Comment by gwsw** [comment]
This seems to be a case of conflicting use cases. Change df1494f was a result of request #6 by @aleclearmind. I believe their case was something like one program writing slowly to a pipe, and he wanted F to continue to display that data until the originating program closed the pipe, and which point the F mode would exit. Your case is multiple programs writing to the pipe by opening and closing it repeatedly, and you want the F mode to persist past the closes. Since your case doesn't work at all with df1494f in place, while #6 was just addressing an inconvenience (having to press ^X when the data is done), I'm inclined to remove the POLLHUP as you suggest.

**Comment by aleclearmind** [comment]
No please, my life literally improve 10x after that.
Can we have a flag?

**Comment by ton** [comment]
Is `-E` not already a flag that would/should cover that case?

**Comment by aleclearmind** [comment]
It's not about quitting upon EOF, it's about unlocking `less` upon EOF.

**Comment by ton** [comment]
Ah, sorry, I misread. In any case I agree that having a flag for it makes sense. But it is a bit confusing to have it be the default behavior IMO. It makes `less +F` behave different from `tail -f` on pipes.

**Comment by gwsw** [comment]
In a68453462d3e0ab8ea7a78877ff5543690ccc102, the F command no longer exits when an input pipe is closed. The new --exit-follow-on-close option can be used to re-enable that behavior.
