### ISSUE TITLE
Any support for lesspipe ?

### ISSUE THREAD

**Issue by kasingal** [gwsw/less#270]
On Debian less package -> it distributes less, lessecho, lesskey, lesspipe
Whereas alpine package is missing lesspipe !

**Comment by gwsw** [comment]
By its nature, a lesspipe script is highly dependent on the operating system it is running on, and what tools are available on that system. Since less is intended to be portable and usable on a wide variety of systems, it would not be feasible to distribute a lesspipe script that works on any system that less can run on.
