### ISSUE TITLE
"Bugs and Enhancement Requests" page ignores GitHub issue tracker

### ISSUE THREAD

**Issue by Chealer** [gwsw/less#354]
Less now uses this GitHub tracker to track its issues. Unfortunately, [the website's _Bugs and Enhancement Requests_ page](http://www.greenwoodsoftware.com/less/bugs.html) only contains a presumably outdated and undetailed list of issues, and does not mention this tracker. This creates a perception of lack of maintenance and reliability.

Please either replace the link with a link to the current tracker, or at least add a link to the current tracker from the page.

**Comment by Chealer** [comment]
Aaah, sorry and thank you very much @gwsw . I did reach it from [an outdated manpage](https://man.freebsd.org/cgi/man.cgi?query=less&apropos=0&sektion=0&manpath=FreeBSD+9.0-RELEASE&arch=default&format=html), which [the English Wikipedia's article](https://en.wikipedia.org/wiki/Less_(Unix)) points to.

I removed the oudated link from the French Wikipedia. That being said, the page could still be removed or at least link to the current tracker.

**Comment by gwsw** [comment]
I have added a note to the page indicating that it is obsolete, with a link to the github bug tracker.

**Comment by Chealer** [comment]
Thanks again @gwsw

**Comment by ferdnyc** [comment]
I've updated the English Wikipedia article to (always) point to the version of the man page for the _current_ FreeBSD release. (When created it had been pinned on FreeBSD 9.0, which is now over 10 years old.)

**Comment by piotr-dobrogost** [comment]
I think it would be better to link to man7's project man page for less.
For comparison:
https://man.freebsd.org/cgi/man.cgi?query=less has man page for Version **608**: 22 Jul 2022
whereas
https://man7.org/linux/man-pages/man1/less.1.html has a man page for Version **633**: 03 May 2023

ps.
Having _cgi_ in the url was cool about 30 years ago… :D

**Comment by ferdnyc** [comment]
@piotr-dobrogost 

Well, that's the thing. AFAIK, "man7's project man page" isn't so much a _project_, it's just Michael Kerrisk's personal site (see https://man7.org/), that happens to include HTML-ified versions of common man pages. (Because he _used to_ maintain the linux `man-pages` tree — he actually stepped down in 2021.) Those pages are generated from... some source? (Presumably some distro, maybe?) The actual `man-pages` _project_ page is https://www.kernel.org/doc/man-pages/, but that doesn't include any man pages in web-viewable form.

I'm not sure it's fair to Kerrisk, to point Wikipedia-level traffic at his personal website. Nor am I sure Wikipedia is likely to consider the personal website of a former Linux kernel tree maintainer to be an authoritative source. Not in comparison to the FreeBSD project site, anyway.

**Comment by ferdnyc** [comment]
In the end, it's an _encyclopedia_. If you need it to contain or link to current, up-to-the-minute information, [you're doing it wrong](https://en.wikipedia.org/wiki/Wikipedia:Recentism).
