### ISSUE TITLE
distinguish q & Q, let latter exit without clearing screen

### ISSUE THREAD

**Issue by jimc** [gwsw/less#36]
less has -XF options (iirc) that suppress clearing of screen on exit.
However, it is inconvenient to choose that before starting the browse.

ISTM it would be easy to assign different exit behavior (already possible)
to some of the :q command variations.  My 1st try would prolly be to
assert those --options just before exit, but thats pure WAG.

**Comment by gwsw** [comment]
The -X flag doesn't specifically suppress clearing the screen, it suppresses (both) the terminal init and deinit sequences. Normally the init sequence is sent when less starts and the deinit is sent just before it exits. If you were to enter less without -X, it would send the init sequence, and if you later chose to exit without sending the deinit sequence, the terminal could be left in an inconsistent state (where arrow keys don't work correctly among other things).  That's why -X is one of the few flags that can't be changed from within less.

**Comment by mcornella** [comment]
Could there be a mode where less always enters and exits the alternate screen, but upon doing so, the last printed page is also printed to the primary screen? Is something like that technically possible? This would fix the use case where a large file is scrolled through and its contents pollute the main screen, when what you really want preserved is what you last saw.

**Comment by gwsw** [comment]
Added --redraw-on-quit option to redraw the final screen after switching back from alternate screen. You can make Q invoke this behavior by adding this line to your .lesskey file.

```
Q toggle-option -!^Predraw-on-quit\nq
```

**Comment by mcornella** [comment]
@gwsw there's a bug when combined with `-F` when the input is smaller than a window, see:

![Captura de pantalla de 2021-09-06 11-17-03](https://user-images.githubusercontent.com/1441704/132192798-599c353f-cf53-4d89-8a9c-af710868d24b.png)

There are two bugs I see here:
1. Both `-F` and `--redraw-on-quit` print the contents.
2. `--redraw-on-quit` prints extra `~` characters.

**Comment by gwsw** [comment]
Should be fixed in dd9a11a4c8e101389bd7095e9dba545102df523d.

**Comment by mcornella** [comment]
Works great now, thanks!

**Comment by gwsw** [comment]
@bew  less-598 is now available for beta testing and includes this feature.

**Comment by bew** [comment]
Thank you @gwsw, is it intentional that using small content (less than terminal height) will add many `~` at the end?

I'd like to not have those, and only see the actual content printed on exit:
With: `LESS= less --redraw-on-quit tmux.conf`
![image](https://user-images.githubusercontent.com/9730330/145641741-9d7c5692-2a1f-4797-a3e3-7976b2d367d7.png)
Then on quit:
![image](https://user-images.githubusercontent.com/9730330/145641835-68b93e67-f6f8-4261-bba8-6edc752a42eb.png)
Instead I'd like it to behave as if the content was just written on exit, similar to a cat:
![image](https://user-images.githubusercontent.com/9730330/145641917-337ebe2c-7605-4364-a801-42c12c1a3638.png)

Do you see what I mean?

**Comment by Chealer** [comment]
Thank you very much @jimc , @gwsw and @mcornella 

Unfortunately this very useful option remains undocumented in [the relevant FAQ entry](https://www.greenwoodsoftware.com/less/faq.html#tite).

**Comment by gwsw** [comment]
I've added a mention of --redraw-on-quit to the FAQ entry.

**Comment by Chealer** [comment]
Thank you @gwsw 
But indicating the minimum version required for that option would be relevant at this time (no Red Hat Enterprise Linux release [nor even Debian](https://packages.debian.org/search?keywords=less) has it).

**Comment by gwsw** [comment]
Ok, done.
