### ISSUE TITLE
lesskey cannot map the `<C-e>` key for line-edit

### ISSUE THREAD

**Issue by sxyazi** [gwsw/less#367]
I am using the Colemak keyboard layout and using `C-e` as down arrow. I tried to map it using lesskey, but it doesn't work:

```ini
#command
/ forw-search
q quit
#stop

#line-edit
^E down
#stop
```

When I press `/` to enter search mode while the prompt appears with `/`, then pressing `C-e` results in the prompt changing to `EOF-ignore /`, but not `down`.

By checking the man page it seems to be a `\e/ forw-search *` thing, but I don't map it in command and the `stop` was in effect. The version of less:

```
less -V
less 633 (PCRE2 regular expressions)
```

**Comment by gwsw** [comment]
Remapping ctrl-E as you have done should work, as long as it is not the first character of a search string (that is, as long as there is already text after the slash). But when the search string is empty, certain control chars, including ctrl-E, are used as search modifiers, and unfortunately for your case, this use takes precedence over the remapped "down" function. Since the search modifiers cannot be remapped, repurposing one for another purpose would lose the functionality of that search modifier.

One possible solution would be to add a new search modifier key that indicates that no more search modifier will follow. You would need to press this key before using the down arrow, which is awkward, but it would be pretty easy to implement. I have not yet thought of any better options or workarounds.

**Comment by sxyazi** [comment]
Yes, it behaves that way. If there is search content, `C-e` works as expected.

In fact, it also had an issue when I tried to map `C-u` to `Up`, which still behaves like `C-u`, i.e. killing the whole line instead of `Up`.

It should be cool if the user key mapping is respected as a priority, in my case I really don't need that modifier (and when I do I will remap it as `forw-search *`)

I'm not sure how much work this would be and if it would break the current behavior. If so, I'll look for other solutions :(

**Comment by gwsw** [comment]
>One possible solution would be to add a new search modifier key that indicates that no more search modifier will follow. 

In 16a526030ee47d364948ac16d67b872840c32abb you can enter ctrl-L at the start of a search string to indicate that the next character should be taken literally and not interpreted as a search modifier. This does require you to enter ctrl-L before your ctrl-E alias, but it will work.

**Comment by sxyazi** [comment]
That's enough, thank you!
