### ISSUE TITLE
-j argument in lesskey causes arg-parsing issues

### ISSUE THREAD

**Issue by rucker** [gwsw/less#393]
Less version: 633 (macOS/Homebrew).

Example lesskey file:
```
#env
LESS = -iR -j.1
#version >= 595 LESS += --use-color --color=Hkc
```

Without  `-j.1`, less functions as configured. Adding the `-j` argument, however, causes something to go wrong with arg-parsing and a log file named `lor --color=Hkc` will be created the next time `less` is invoked. It seems that in this scenario, less will interpret the first "o" in "color" to be the `-ofilename` argument.

Unsuccessful attempted workarounds:
- Using an integer value for `-j` instead of a decimal
- Expressing the arguments as `-iRj.1`

What did work: placing `-j` before the other args, i.e. `-j.1 -iR`.

**Comment by gwsw** [comment]
I think this is the same issue as #380. You can fix it by appending a space to the end of the first line, after ```-j.1```. I have added a note to the lesskey man page to make this issue clearer.

**Comment by rucker** [comment]
Thank you for the fast response! Adding a space to the end of the line in question does prevent the issue from occurring.

What's interesting though is that I don't seem to have this issue without a trailing space for options other than `-j` (not that I have found anyway). I tried with other options that take a positional argument such as `-b128` and `-n0` and I didn't observe any issue with them, even without the trailing space. Unless I'm missing something, it seems like there is something peculiar about the `-j` option.

**Comment by gwsw** [comment]
Yes, -j is parsed differently from -b because -j can begin with a "." or "-". The parser uses a somewhat crude mechanism that accepts all digits, dots, and dashes, in any position as the -j parameter. What's happening here is your LESS variable was being set to "```--iR -j.1--use-color --color=Hkc```". The parameter of the -j was then taken to be "```.1--```". Then when it went on to parse the next option, it was just "```use-color```"; the leading "```--```" had already been consumed so it didn't recognize that this was a long option name. This algorithm could be improved so that -j consumes only leading dashes and not dashes anywhere.

**Comment by gwsw** [comment]
Parsing of -j (and -x and -#) options has been improved in 065f3e42b292880d9fc89e01ad8518d451e53e35. -j now accepts only one leading dash as a minus sign, not arbitrary dashes anywhere in the string.
