### ISSUE TITLE
Output differs (and is wrong) from cat on colored file from stark/Color-Scripts

### ISSUE THREAD

**Issue by ericonr** [gwsw/less#41]
`less` version: 551 (PCRE regular expressions)

I was taking a look at the colored terminal scripts from stark/Color-Scripts, and one of them was, instead of a script, a text file that had to be printed to STDOUT to be visualized. It was the [crowns](https://github.com/stark/Color-Scripts/blob/master/color-scripts/crowns) file. When shown using

`less --RAW-CONTROL-CHARS crowns`

it shows a different (wrong) result than when simply printing it to the terminal (using `cat`).

The output from both commands (`cat` and `less` through `bat`) can be seen in [this asciinema](https://asciinema.org/a/VbOcftWUTgdy7LbenjtolpQd1).

I have verified the same behavior in both Konsole and Alacritty, and have guaranteed that my terminal was wide enough for the file to be printed on it.

I first realized this problem in [this issue with `bat`](https://github.com/sharkdp/bat/issues/771).

**Comment by gwsw** [comment]
The problem with the crowns file is it contains cursor-movement commands. There are numerous instances in the file of "ESC [ nn C" sequences to move the cursor right. This will behave differently on different terminals. It might work if you use -r but that's not recommended due to the potential for display problems if the embedded cursor movements interfere with less's management of the screen.

**Comment by ericonr** [comment]
Yeah, it did work with `-r`. I also added `-f` so it didn't show the prompt asking if I wanted to read a binary file. Thanks!

That said, should I close the issue?
