### ISSUE TITLE
Allow headers to be defined using regular expressions

### ISSUE THREAD

**Issue by ericpruitt** [gwsw/less#436]
I like the "--header" option, but I wish it were possible to specify headers using regular expressions. This would be useful when, for example, looking at long diffs where the file name might be scroll out of view or looking at man pages and figuring out which section you're reviewing without having to scroll back. Ideally, it'd be nice to be able to specify the number of lines of context before and after the diff, but even showing a single line would be useful.

**Comment by bew** [comment]
This would integrate nicely with [`delta`](https://github.com/dandavison/delta) and be a basic replacement to [`ov`'s section system`](https://github.com/noborus/ov#39-section)

**Comment by gwsw** [comment]
Just to make sure I understand this proposal, you're asking for an option where you'd specify a regular expression, and the first line in the file that matches that pattern would always be displayed as the first line on the screen? Is that correct? Maybe it make more sense to use a line number instead of a pattern, to avoid ambiguity about what should be done if no line matches the pattern, or if more than one do.

**Comment by ericpruitt** [comment]
No, the idea is that when you scroll past a line matching the regular expression, it becomes the new header.

If it was possible to specify multiple header lines, that could suffix, but it becomes more complicated when you're using less to view ephemeral data that way which is why I would prefer regular expressions.

**Comment by gwsw** [comment]
In that case the header displayed at a certain position in the file would be nondeterministic. It would depend on how you reached that point in the file -- scrolling there might show one header, but jumping there via the g or p command would show a different header. Is that the intended behavior?

**Comment by ericpruitt** [comment]
No, that's not the intended behavior. I would expect the implementation to search backwards for a matching header if the user moves in discontinuous manner. The process could be optimized with some caching and keeping track of which lines have been searched for header matches to reduce the search space.

**Comment by gwsw** [comment]
Using a regular expression to define headers turned out to be rather awkward to implement. It also seems to me to be less than useful in cases where there isn't a clear pattern that can capture all header lines. Instead, in a1a6f610ea0a260ac443d08b90bca922e3142b0a I have enhanced the --header option so that it sets the first line on the screen to be the header line. This can be issued as needed to select different lines as header lines.
