### ISSUE TITLE
Jumping (via 'g') with a `--header` doesn't work correctly.

### ISSUE THREAD

**Issue by nestor-custodio** [gwsw/less#444]
Jumping (via 'g') calculates which line should be first on the display, but doesn't account for the header, making the requested line not actually visible after scrolling.

I'd *imagine* this is also an issue when jumping with 'p' instead, but between working with percentages and dealing with rounding, etc, I found it more difficult to accurately calculate which line I should expect to see at the top. 🤷

---

Steps to reproduce:

- Running `( echo 'some-header' ; seq 100 200 ) | /bin/less --LINE-NUMBERS --header=1` yields:
  ```
    1 some-header
    2 100
    3 101
    4 102
    5 103
    6 104
    7 105
    8 106
    9 107
   10 108
  ```
- Entering `25g` should jump to line 25, and it **sorta** does:
  ```
    1 some-header
   26 124
   27 125
   28 126
   29 127
   30 128
   31 129
   32 130
   33 131
   34 132
  ```
- Notice the requested line (25) is "behind" the header.

---

Version used:
```
less 633 (GNU regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by gwsw** [comment]
Yes, see the note in the man page regarding the --header option:

>(Note that it may be necessary to
              change the setting of the -j option to ensure that the
              target line is not obscured by the header line(s).)

**Comment by nestor-custodio** [comment]
🤦 My bad, I missed that. Thanks for the shout.

I would still argue there's a problem here, however. The existing manpage text essentially says "if you use `--header` with an **N** value, you *must* specify a `--jump-target` < 1 or > **N**, otherwise you'll never actually see the requested line after jumping *without additional scrolling*", which definitely *feels* like a bug (or at the very least something `less` should be managing on its own).

IMO, either:
- the `--jump-target` should *default* to the `--header` **N** value + 1
... or even better ...
- the "addressable" line space should be defined such that jump target "1" is the line immediately below the header (if any). The consequences of this change would be:
  - It's impossible to set a jump target such that the user can ever jump to a line that's obscured by the header.
  - Fractional jump target values will work *as intended*: a `--jump-target='.5'` will display about (±1) the same number of "data lines" (i.e. non-header lines) above and below the target.
  - Jumping to a line <= **N** should result in no scrolling at all, since that line is always visible. (Jumping to the start of document without having to remember how many header lines are in play would still always be easily doable via 'g'/'<'.)

---

You're welcome to close this issue, as your comment above does provide a workaround for my original problem, but I did want to provide the above feedback as suggestions for more sensible behaviours when a header is in play.

**Comment by gwsw** [comment]
I had originally planned something like your second proposal, but it felt potentially confusing. Say a user has -j2 and is therefore used to looking at the second line on the screen for their target. Now with --header=1 the target is at line 3. Or if they use a negative offset like -j-4, it's not clear whether that should adjust for header lines. Or if they have a large header (--header=20), then fractional -j options could be very confusing (-j.5 would be nowhere near the middle of the screen). Ultimately I don't really like the idea of the target line changing based on whether --header is used, although I can see arguments for both approaches. Ultimately since -j is under the user's control, I chose to leave -j relative to the start of the screen as it always has been.

On the other hand, it does seem reasonable to have the default be the line after the header if the user does not specify any -j. I will look into doing this.

**Comment by gwsw** [comment]
After some consideration, I've made a change in bcd42b1494eb68aae978337c1b26e62428305d1a. The parameter to the -j option still refers to an absolute screen line without consideration of any headers, but if you set the target line to a line which would be obscured by a header, the target is moved down to the first unobscured line.

**Comment by nestor-custodio** [comment]
Much appreciated!
