### ISSUE TITLE
with -X (while without --mouse), scrolling is broken for VTE terminal

### ISSUE THREAD

**Issue by calestyo** [gwsw/less#445]
Hey.

I recently noted that when using [delta](https://github.com/dandavison/delta) (which in turn runs `less`) via `git`, scrolling doesn't work.<br>
Others have had that problem before ([[0]](https://github.com/dandavison/delta/issues/58), [[1]](https://github.com/dandavison/delta/issues/630)) with one solution being to simply use `--mouse`.

While that works, I noted that scrolling with `--mouse` is different (slower, feels less "natural") than without (which normally works for me, with plain `less` and even with plain `delta` when no `git` is involved).

Turns out:
- `less` scrolling works without `--mouse` on at least VTE-based terminals, but not e.g. on `xterm`
- `git` sets `X` (and some others) in the `LESS` env var
- `-X` is causing the scrolling to no longer work on VTE-based terminals
- `git` uses `X` to avoid that the screen is cleared when `less` is exited [[3]](https://lore.kernel.org/git/eadc03fc56d530ea31790f8a4b47a16e@manjaro.org/T/#m245af0e6a02b345dbae1371d7ff957ec5b38fc0a)

Is it possible to make `-X` not break scrolling for VTE?

And if not, is it possible to just get the "don't clear" functionality without whatever breaks scrolling for VTE (presuming that this might come from the `Disables sending the termcap initialization` and not from the ` and deinitialization` part of `-X`’s functionality)?

Thanks,
Chris.

**Comment by avih** [comment]
> Is it possible to make `-X` not break scrolling for VTE?

The short answer is no, details below, but first:

What problem are you trying to solve?

Is it that you want to leave the content on screen after the pager exits, and also use the mouse wheel to scroll, but if you use `-X` to leave the content on screen then it doesn't scroll, and if you add `--mouse` then you don't like how it scrolls.

And the problem is that you don't know how to get both "stay on screen after exit" and "nice scroll" together?

If not, then please descrtibe the actual problem you have, not the possible solutions you think might work (hint: "make -X not break scrolling for VTE" is a possible solution, it's not the problem).

If yes, then first, what you call "unnarutal" scroll is most probably number of lines per mouse wheel scroll, which defaults to 1 with `--mouse`.

So wherever you're using `-X` and `--mouse`, you can add `--wheel-lines=3` (or 5, or any other number which will feel more natural to you) to change it. You should be able to find a value that will make it scroll like when not using `-X` and `--mouse`. Check the manpage for other things which `--mouse` does.

However, this will not necessarily leave the whole content on screen. E.g. if you page up/down before exiting `less`, then it might overwrite some of the content, and after `less` exits you may or may not be able to see the full content start-to-end.

An alternative solution is not to use `less` at all (or any other pager). Instead, just let it print the diff to the terminal and finish/exit. Then the mouse wheel will scroll the terminal scrollback buffer - where the colored diff exists. You don't need `less` to scroll back what was printed to the terminal. Many terminals also support searching the scrollback, and paging it (e.g. maybe ctrl+shift+f to search, ctrl+shift+pageup/down to page).

Now to the explanation how it scrolls even without `--mouse` in VTE but doesn't scroll when using `-X`:

Here are two things applications can request and most terminals support:
1. Request to use the "alternate screen". This switches to a different internal terminal screen without scrollbar, and without scrollback. It's mainly useful for full-screen TUI applications (interactive text user interface), like `vim`, or `emacs`, or `less`, etc. Right before the application exits, it tells the terminal to switch back to the main screen (with the scollbar and scrollback and the whole terminal history),
2. An application can request mouse events from the terminal. If it does that, then the terminal starts sending mouse events - like wheel scroll and mouse clicks to the application.

Less does request to use the alternate screen by default, and doesn't request mouse events by default.

`-X` tells less "don't initialize the terminal with special capabilities (like using the alternate screen). Instead, use the main screen". A side effect of that is that when `less` exits then some content stays on the main screen (with the scrollbar and the shell history), because it didn't use the alternate screen.

And obviously `--mouse` makes `less` request mouse events from the terminal, and one thing it does with them is to scroll the content on wheel events.

So how does it scroll without `--mouse` (when not using `-X`)?

The answer is that some terminals make an educated guess, that if an application requests the alt-screen, but doesn't request mouse events, then instead of simply ignoring the mouse events, the terminal tries to make them useful, so the terminal converts mouse wheel events into one or few up/down arrow key presses (or some other keys which a TUI application is likely to interpret as scroll up/down, like `^E` and `^Y`),

But it's a guess that the user will want that. If the application does some destructive things with `^E`, like deleting files, then it's not obvious that the user would want to translate mouse wheel events into file-shredding commands...

So that's what VTE terminals do: translate mouse wheel to keypresses if the application requested alt screen but not mouse events.

But when using `-X` then `less` doesn't use the alt-screen, and the terminal can't know whether it's a TUI application or some shell or even some non-interactive app which just prints things to screen slowly. So it can't afford to translate mouse events to key presses, because this can result in various unwanted things. And so mouse wheel scroll doesn't work, unless also adding `--mouse` so that `less` itself handles it.

**Comment by gwsw** [comment]
I'm unclear on what the original report means by "scrolling doesn't work". At first I thought this mean the directional keys (arrows, j, k, etc) don't work. But reading between the lines, I think maybe it means scrolling with the mouse wheel doesn't work?

In any case, -X is a risky flag, because it disables the "smcup" initialization that is documented as being required before using cursor addressing. Some terminals will work with -X but as you have discovered, not all will. If the goal is to leave text on the screen after less exits, two possible solutions which don't use -X are:

1. Change your terminfo entry so that smcup doesn't switch to an alternate screen, but still does the initialization required to make mouse scrolling work. On many systems you can do this by extracting the terminfo entry with infocmp, modifying the smcup entry, and then recompiling the entry with tic.
2. Use the --redraw-on-quit option in less. This makes less redraw the final screen AFTER switching back from the alternate terminal to the normal one.

**Comment by calestyo** [comment]
Hey.

First, yes I meant scrolling with the mouse, sorry for being not clear enough.

> What problem are you trying to solve?

It's really mostly just what mentioned above, when using git (and `LESS` is not already set) it sets per default `LESS=FRX`, which then affects `less`, causing the mouse wheel scrolling under VTE based terminals to no longer work (under e.g. `xterm` it anyway works only if `--mouse` is used).

Ideally it would be nice if this just works out of the box, but that's not even the main point.<br>
I may wish that this VTE-specific mouse scrolling also works while still having `less` clear the screen on exiting.

I say “may”, because at least on all terminals I've now test and various distributions, there's some mess up, when one does **not** let `less` clear the screen (i.e. when `-X` is used) and when one did scroll (mouse or cursor) up/down/up in the pager. So I'm no longer that sure, whether I actually want `-X` at all.<br>
There was [some discussion around this on the git mailing list](https://lore.kernel.org/git/eadc03fc56d530ea31790f8a4b47a16e@manjaro.org/T/#m4032431a919eb785efa34d02cde1e161b86d945f) with one person reporting that he doesn't see that problem. I've also made a [video](https://youtu.be/MsxtQgrKM50) of it.

> Is it that you want to leave the content on screen after the pager exits, and also use the mouse wheel to scroll, but if you use -X to leave the content on screen then it doesn't scroll, and if you add --mouse then you don't like how it scrolls.

So yes it's mostly that, plus that ideally it would work out-of-the box on VTE.


> So wherever you're using -X and --mouse, you can add --wheel-lines=3 (or 5, or any other number which will feel more natural to you) to change it. You should be able to find a value that will make it scroll like when not using -X and --mouse.

That makes it better, though it's still somewhat different. With `--wheel-lines=n` it really scrolls `n` lines. Not sure what VTE does, but I can scroll just one single line with it, yet it still gets much "faster" than `--mouse` with `n=1`.<br>
Anyway, that minor difference is not really the point of this report... I merely just thought it could be made working with VTE even without the `--mouse`.


> However, this will not necessarily leave the whole content on screen. E.g. if you page up/down before exiting less, then it might overwrite some of the content, and after less exits you may or may not be able to see the full content start-to-end.

Tell that on the git mailing list ;-)

> An alternative solution is not to use less at all (or any other pager).

Sure, but that won't work in practise on any larger repo when doing e.g. `git log` and you get the log for some gazillion commits ;-)

> and doesn't request mouse events by default.

Just out of curiosity, what is the reason to not do so and rather provide a disabling option?

Thanks anyway for the good explanation why this cannot be made work out of the box with that heuristics VTE employs.


Also thanks for the pointer to `--redraw-on-quit`... seems like a good compromise, especially one that hopefully doesn't cause that issues I see when going down/up/down in less.


Since there is by design no real way to "fix" this... I close the issue.

Thanks,
Chris.

**Comment by gwsw** [comment]
>Just out of curiosity, what is the reason to not do so and rather provide a disabling option?

This is for backwards compatibility, so that less's behavior with respect to the mouse wouldn't unexpectedly change after updating less (mouse support was implemented in less-551).

**Comment by calestyo** [comment]
Okay, but wouldn't the behaviour anyway change **only** if someone actually uses the mouse in less - and then probably wants it to work?

**Comment by gwsw** [comment]
The mouse would do whatever the terminal does with mouse actions. Some terminals would scroll back in the terminal buffer, and the user may want that old behavior. Or, on some terminals, enabling the mouse disables text selection, and again, the user may want the old behavior that allows text selection.
