### ISSUE TITLE
Supressing or hiding of the less prompt.

### ISSUE THREAD

**Issue by Momijie** [gwsw/less#450]
I want to disable or at least hide the prompt bar. Is this possible currently? If not is there any interest in a feature like this? 
This goes hand in hand with greater customization of the prompt bar up to current modern standards of changing the look and feel of ones application.

**Comment by gwsw** [comment]
You cannot disable the prompt line, in the sense that less would use it for file text rather than for a prompt. The prompt line is needed for various purposes besides showing a prompt, such as entering a search pattern, entering digits of a parameter, displaying status and error messages, etc. It seems like it would be awkward to keep showing and hiding file data in the last line depending on the state of the UI. Is there a specific use case where it would be useful to hide the prompt line?
