### ISSUE TITLE
Cannot set `$` as literal pattern at command line (less -p'\$')

### ISSUE THREAD

**Issue by telychko** [gwsw/less#451]
ENVIRONMENT

$ less --version
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

STEPS TO REPRODUCE:
1. Run `less -p'\$' .bash_profile` or `less '+/\$' .bash_profile`

ACTUAL RESULTS:
less reports `\ at end of pattern  (press RETURN)`

EXPECTED RESULTS:
It should jump to line that contain `$`

**Comment by gwsw** [comment]
You need to use the --use-backslash option to enable backslash processing in command line options; see the description in the man page. You also need to escape the backslash and dollar sign an extra time, so that they are processed by both the command line option processor and the regular expression library:
```
less --use-backslash -p'\\\$' file
```

**Comment by telychko** [comment]
Is there any reason why is the rest of special symbols treated correctly except `$`?

I can run `less '+/\[\[\^\..\(\)\|\*\+\?\{\\]' file` with no problem.

**Comment by gwsw** [comment]
Yes, the dollar sign has special meaning in a less option string as an end-of-string indicator. See the description in the man page under OPTIONS and under --use-backslash. Other metacharacters which have special meaning in regular expressions don't have special meaning in a less option string.

**Comment by telychko** [comment]
I see. Thank you so much. The manual describes that moment.
