### ISSUE TITLE
Support for sixel image format in less

### ISSUE THREAD

**Issue by ploum** [gwsw/less#477]
Proposal : adding support for images encoded using the sixel format in less.
https://en.wikipedia.org/wiki/Sixel

Usecase :  Offpunk is a CLI webbrowser which translates HTML pages to ANSI, save the result in a file then open it in less.

Images are converted to ANSI symbols using Chafa. See screenshot on:
https://sr.ht/~lioploum/offpunk/

Chafa: https://hpjansson.org/chafa/

Chafa also supports encoding images to the sixel format, which would be a lot less useful but is not supported by less.

Proposal would be to allow less to understand sixel images and display them (probably when enabled using a paramater).

For terminals supporting sixel, see:
https://www.arewesixelyet.com/

**Comment by gwsw** [comment]
Can't you use a LESSOPEN preprocessor to do this conversion? It seems a rather specialized feature to add to less itself.

**Comment by ploum** [comment]
I’m not really a specialist but I don’t think any preprocessing could help.

The way I see it (which may be wrong) is that the sixel protocol is doing to pixel what ANSI is doing to characters. So any rendering has to be done in less itself  (you could not preprocess ANSI).

But I have no idea how hard it could be. 

All I know is that I could take the following file and do "cat sixel.txt" in my terminal : it will display a picture.

But "less sixel.txt" is full of garbage.

[sixel.txt](https://github.com/gwsw/less/files/14202635/sixel.txt)


(I want to be clear that I’m launching a discussion about the subject here because I find it interesting. I have no preconceived opinion on what could or should be done.  Thanks a lot for your work on less !)

**Comment by ploum** [comment]
Oh yeah, with your examples, it works in xterm. That’s really interesting so it seems my own issues are not related to less but probably to the terminal (and also to my own sixels files)

**Comment by gwsw** [comment]
FWIW, the Wikipedia article says sixel sequences begin with ```ESC P ... q```, but your sixel.txt file seems to be a different format; it contains sequences that begin with ```ESC _ G```.

**Comment by ploum** [comment]
yes, I messed up the file. This version should be valid:

[sixel.txt](https://github.com/gwsw/less/files/14234153/sixel.txt)

**Comment by gwsw** [comment]
Based on the message from @ploum on Feb 8, it sounds like this is not a less issue.

**Comment by AeliusSaionji** [comment]
There is a problem here, and the resolution can only come from less, although you may not consider it strictly less' problem.

I am not an expert, but from the behavior I can make guesses as to what's going on.

## Problem 1
The sixel exists on one line, and terminal emulators with sixel support must interpret the sixel control codes such that the result is properly integrated into the scrollback.

Less is a terminal emulator (of sorts) and has no support for sixel. Sixels are not integrated into its scrollback.

If the exact line where the sixel exists is visible to the _external_ terminal emulator, said terminal can paint the image.

But the moment that sixel line is scrolled out of view: poof, the whole image is gone. Ideally, we'd be incrementally scrolling the image out of view line by line.

I think this would require dynamically rewriting the sixel to crop/uncrop the image as we scroll. Some sixel control code must be visible to the external terminal; for as long as the image logically would be.

## Problem 2
Because less' terminal emulation is not sixel aware, less does not provide space for the image to exist. An image that is 5 lines tall will overlap with the next 5 lines of output.
