### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by spaette** [gwsw/less#502]
Dumped repo strings exposed a few typos.

BRACKET
Miscellaneous
Traditional
character
multibyte
receiving

```
$ grep -nr BRAKCET less
less/unicode/EastAsianWidth.txt:1720:FE18           ; W  # Pe         PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRAKCET
less/unicode/UnicodeData.txt:16451:FE18;PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRAKCET;Pe;0;ON;<vertical> 3017;;;;N;;;;;
$ grep -nr Miscellanous less
less/lesstest/lt/version.c.lt:76:v23    5/25/85  Miscellanous changes and prettying up.
less/version.c:43:v23    5/25/85  Miscellanous changes and prettying up.
$ grep -nr Traditinal less
less/tags.c:692: *      o Traditinal Ctags with -x option
$ grep -nr charcter less
less/search.c:1271:     /* oline points to charcter ch, line points to the one after it. */
$ grep -nr mulitbyte less
less/lesstest/lt/version.c.lt:664:v376  6/10/02   Fix bug in overstriking mulitbyte UTF-8 characters
less/version.c:631:v376  6/10/02   Fix bug in overstriking mulitbyte UTF-8 characters
$ grep -nr "receiv ing" less
less/lesstest/lt/version.c.lt:108:                ignore SIGTTOU after receiv ing SIGTSTP.
less/version.c:75:                ignore SIGTTOU after receiv ing SIGTSTP.
$ 
```
<hr>

as per @gwsw below, files under unicode directory originate externally from this repo

**Comment by gwsw** [comment]
The first typo ("BRAKCET") is in files downloaded from the Unicode Consortium. Less can't fix that, and in fact the Consortium themselves can't fix it because of the rule that published character names cannot be changed [even to fix an error](https://en.wikipedia.org/wiki/Unicode#Anomalies).

I have fixed the four typos in source code comments in 2ef383e210814111516b0490bf9201c4db499351. I have not fixed the ones in .lt files since those are binary files that are used by lesstest and normally never viewed by humans, and changing them would involve rebuilding the tests, which might become complicated and cause the tests to no longer test what they were designed to test.
