### ISSUE TITLE
How to configure control-left and control-right to be recognized by less?

### ISSUE THREAD

**Issue by minnesjay** [gwsw/less#511]
^LeftArrow and ^RightArrow do not go to the first and last column respectively. 
Is there a lesskey configuration that fixes this if less does not recognize the ctrl key on a platform?

**Comment by gwsw** [comment]
What operating system are you running on? There is no standard way for less to determine the sequence sent by ctrl+arrow keys on Linux (if the terminal even sends anything for such keypresses; some terminals just ignore it) because terminfo and termcap do not support such keys. So there are two choices: you can either use the alternate commands (```ESC-{``` or ```ESC-}```), or define terminal-specific commands in your lesskey file. For example, if you know that your terminal sends ```ESC[1;5D``` for ctrl+left-arrow and  ```ESC[1;5C``` for ctrl+right-arrow, you could add these lines to your lesskey file
```
\e[1;5D no-scroll
\e[1;5C end-scroll
```
But this would only work with that specific type of terminal.
