### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by elig0n** [gwsw/less#526]
tested with both `less-657` release and 25d08b3

**Symptom:** the mere existence of `~/.config/lesskey` causes coredump:

```
$ touch ~/.config/lesskey
$ ./less --help
free(): double free detected in tcache 2
[1]    2446414 IOT instruction (core dumped)  ./less --help
$ rm -f ~/.config/lesskey
$ ./less --help
# .... as usual ...
```

This is the stack trace:

```
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, Name: "less", stopped 0x7ffff7d9932c in ?? (), reason: SIGABRT
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
[#0] 0x7ffff7d9932c → mov ebx, eax
[#1] 0x7ffff7d486c8 → raise()
[#2] 0x7ffff7d304b8 → abort()
[#3] 0x7ffff7d31395 → test DWORD PTR [rbx], 0x8000
[#4] 0x7ffff7da32a7 → nop WORD PTR [rax+rax*1+0x0]
[#5] 0x7ffff7da5799 → lea rdi, [rip+0x106d70]        # 0x7ffff7eac510
[#6] 0x7ffff7da7e93 → free()
[#7] 0x555555579f21 → parse_lesskey(ainfile=0x5555555969e0 "/home/user/.config/lesskey", tables=0x555555591240 <tables>)
[#8] 0x555555564e0a → lesskey_text(filename=0x5555555969e0 "/home/user/.config/lesskey", sysvar=LFALSE, content=LFALSE)
[#9] 0x555555565020 → add_hometable(call_lesskey=0x555555564ea0 <lesskey_src>, envname=<optimized out>, def_filename=0x55555557b934 ".lesskey", sysvar=LFALSE)
```

Since "double free" error mean that the same memory is freed twice consecutively I looked but I couldn't find more than instance one of `free(lesskey_file);` in `lesskey_parse.c`.
But removing [line 620 that was added here](https://github.com/gwsw/less/commit/f1bc6a93cde5617475c56a612b26c7935acbd4e3#diff-3852043baac026abee7a9739f31567cfd5f1860d37a2b1bc97c5724670803bb9R620) avoids the problem.
From my little knowledge It looks that`lesskey_file` is somehow not NULL when the condition is checked.

**Comment by avih** [comment]
As far as I can tell, `lesskey_file` can be double-freed only if `parse_lesskey` is called more than once (it's assigned from `infile`, then `infile` is freed, then at the next call `lesskey_file` is freed (again) because it's not NULL.

I don't know whether it can be called twice, but judging from the bug report - it can, and this _should_ fix it:
```diff
diff --git a/lesskey_parse.c b/lesskey_parse.c
index 06e3d5f..19b7d4a 100644
--- a/lesskey_parse.c
+++ b/lesskey_parse.c
@@ -643,7 +643,6 @@ int parse_lesskey(constant char *ainfile, struct lesskey_tables *tables)
 		/* parse_error("cannot open lesskey file %s", infile); */
 		return (-1);
 	}
-	free(infile);
 
 	/*
 	 * Read and parse the input file, one line at a time.
@@ -654,6 +653,8 @@ int parse_lesskey(constant char *ainfile, struct lesskey_tables *tables)
 		parse_line(line, tables);
 	}
 	fclose(desc);
+	free(infile);
+	lesskey_file = NULL;
 	return (errors);
 }
 
```

Note that the free and NULL assignment are moved to after the parsing, because I presume `lesskey_file` can be used in error reports during the parsing.

Unrelated to the double-free, I think `parse_lesskey` may try to `strcmp(NULL, ...)` and `fopen(NULL, ...)`:
```c
int parse_lesskey(constant char *ainfile, struct lesskey_tables *tables)
{
	FILE *desc;
	char line[1024];
	char *infile = (ainfile != NULL) ? strdup(ainfile) : homefile(DEF_LESSKEYINFILE);
	if (lesskey_file != NULL) free(lesskey_file);
	lesskey_file = infile;

	init_tables(tables);
	errors = 0;
	linenum = 0;
	if (less_version == 0)
		less_version = lstrtoi(version, NULL, 10);

	/*
	 * Open the input file.
	 */
	if (strcmp(infile, "-") == 0)
		desc = stdin;
	else if ((desc = fopen(infile, "r")) == NULL)
	...
```

Because `infile` may be `homefile(DEF_LESSKEYINFILE)` - which may be `NULL`, and at the bottom of the code above there's `strcmp(infile, "-")` and also likely `fopen(infile, "r")` without a test of whether `infile` is NULL that I can tell.

While most libc implementations are likely to test the pointer for NULL, It's not something POSIX mandates as far as I can tell, so it's probably undefined behavior.

Also unrelated to the double-free, `homefile` on Windows seem to also search in the current dir, which I think is a security issue, because if someone downloads a malicious zip and extracts it, then cd into that dir, and then tries to use "less" with one of the files, if a file `$PWD/_lesskey` exists (the lesskey file name on windows), then I believe it can map key presses to malicious shell commands.

**Comment by avih** [comment]
> At least on Windows XP and later `${HOMEDRIVE}${HOMEPATH}` should exist and is the home dir

I see that `main()` in `main.c` already sets HOME to this value on Windows on startup, so I think the `_searchenv` call can be removed.

I see that the LESSKEY[IN]FILE values do have a _SYS variant which is at the root of the c: drive (I didn't examine the logic of using the sys value), but LESSHISTFILE doesn't have a sys variant, so I don't know what it should try to use if the HOME value is invalid. I'd say disable the history file in such case.

**Comment by gwsw** [comment]
I think this only happens if there is a system lesskey file as well as a local one, which causes parse_lesskey to be called twice. As avih noted there were a couple of other memory handling bugs in parse_lesskey, and there was yet another one in parse_lesskey_content. All of these should be fixed in 1649cc355a9eb824837feb4359828f5627e2eb69.

**Comment by avih** [comment]
> All of these should be fixed in [1649cc3](https://github.com/gwsw/less/commit/1649cc355a9eb824837feb4359828f5627e2eb69)

LGTM.

What about disabling CWD in `homefile` on Windows, e.g. using this patch:
```diff
diff --git a/filename.c b/filename.c
index 8706629..d6e843e 100644
--- a/filename.c
+++ b/filename.c
@@ -288,7 +288,7 @@ public char * homefile(constant char *filename)
 	if (pathname != NULL)
 		return (pathname);
 #endif
-#if MSDOS_COMPILER || OS2
+#if (MSDOS_COMPILER && MSDOS_COMPILER!=WIN32C) || OS2
 	/* Look for the file anywhere on search path. */
 	pathname = (char *) ecalloc(_MAX_PATH, sizeof(char));
 #if MSDOS_COMPILER==DJGPPC
```

DJGPP/borland/ms-dos-compiler and OS2 (assuming they even compile) remain with the same behavior as before which does look first at CWD, because I don't know whether these systems have something which can be considered $HOME. I'd guess at least the DOS variants don't have HOME.

**Comment by gwsw** [comment]
At this point I'm trying to get the release out and am taking only very critical changes like crashes and other obvious misbehavior. Your suggestion seems reasonable for the next release but I don't think it should go into the current release. Please open a new issue for this change so we can track it separately from the double free bug.

**Comment by avih** [comment]
I understand.

The reason I hoped to get it in for this release is that hopefully it would be unnoticeable, limited to Windows, and the issue is already known and can be targeted for possibly a long while till the next release happens. My line of thought is that if this results in backlash - which I think shouldn't happen, then in the worst case you can make an additional release/fix to revert it, but otherwise Windows user would have this issue fixed.

I did open a PR for it, and I'm leaving it up to you.
