### ISSUE TITLE
Shift+Space should scroll in the opposite direction of just SPACE

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#536]
In browsers SHIFT+SPACE scrolls in the opposite direction of just SPACE.
Alas in less they both go in the same direction.

**Comment by gwsw** [comment]
By default, almost all terminals treat SHIFT-SPACE the same as plain SPACE. In other words, there's no way for less to tell whether the SHIFT key is being held down when SPACE is pressed. You could reconfigure your terminal to send a unique sequence when SHIFT-SPACE is pressed. But since there is no terminfo entry for such a thing, you'd need to add a corresponding entry to your lesskey file. I found some discussions of this here (related to both less and vi):

https://unix.stackexchange.com/questions/88579/shift-space-in-less
https://zacwe.st/2021/09/16/making-shift-space-send-page-up-and-other-key-mappings-in-iterm2/
https://www.reddit.com/r/vim/comments/2qns4a/how_to_map_sspace_in_terminal_vim/
https://stackoverflow.com/questions/279959/how-can-i-make-shiftspacebar-page-up-in-vim
