### ISSUE TITLE
man page implies that `-+` should work for numeric-valued options

### ISSUE THREAD

**Issue by injust** [gwsw/less#574]
The man page says:

> -+     Followed by one of the command line option letters this will reset the option to its default setting and print a message describing the new setting.  (The "-+X" command does the same thing as "-+X" on the command line.)  **This does not work for string-valued options.**
> 
> -!     Followed by one of the command line option letters, this will reset the option to the "opposite" of its default setting and print a message describing the new setting.  **This does not work for numeric or string-valued options.**

Which implies that `-+` should work for numeric-valued options. But it didn't work when I tested with `-+j`. So 1) I think the man page needs to be updated to mention that it doesn't work for numeric-valued options, either.

2\) The error message is `Cannot use "-+" or "--" for a string option`. I think `--` should actually be `-!`? And it should probably mention numeric options too.

3\) It might be clearer if `less` referred to options that aren't numeric/string-valued as boolean options instead.

**Comment by gwsw** [comment]
There are several issues here.
1. The message ```Cannot use "-+" or "--" for a string option``` dates from a time before long option names (starting with ```--```) were supported. At that time ```--``` was used for the feature currently invoked by ```-!```. The message should have been changed when long option names were introduced but was overlooked until now. I will change it.
2. I don't think it would  be too hard to make ```-+``` work for numeric options. However ```-j``` in particular is not numeric; it is a string option because "numeric" means "integer" and -j can take a leading decimal point. It may be best to leave ```-+``` as it and correct the documentation as you suggest, but I'll look into this.
3. There are actually four kinds of options: numeric, string, boolean and triple-valued. Triple-valued options have a lower-case and upper-case variant, like ```-a/-A``` ```-g/-G```, etc. The documentation could refer to options that are not numeric/string as "boolean or triple-valued" but I don't know if that would be much clearer.

**Comment by injust** [comment]
Thanks for the quick response!

> The documentation could refer to options that are not numeric/string as "boolean or triple-valued" but I don't know if that would be much clearer.

I think that might make things even more confusing. Probably best to stick with "numeric/string-valued options". I think it only appears in 2 places in the man page, anyway.

**Comment by gwsw** [comment]
Fixed the "Cannot use ..." message in 9c7105e01f9de65f66fba73d11db12860e533d6c.

**Comment by gwsw** [comment]
And to address the first point in this report, the ```-+``` or ```--+``` syntax CAN be used with numeric options, but only truly numeric (integer) options like ```-h```, ```-y```, ```--line-num-width```, ```--status-col-width```, etc. It does not work with options that are internally strings because they accept a decimal point, like ```-j```, ```-#```,  etc.
