### ISSUE TITLE
less is not reproducible when built from git

### ISSUE THREAD

**Issue by bbhtt** [gwsw/less#583]
It's generating timestamps that cause the issue.

See 

1. https://github.com/gwsw/less/blob/e77e1176c80cca989694818866ae6cd7e7707161/mkhelp.pl#L10-L12
2. https://github.com/gwsw/less/blob/e77e1176c80cca989694818866ae6cd7e7707161/mkhelp.py#L6-L9
3. https://github.com/gwsw/less/blob/e77e1176c80cca989694818866ae6cd7e7707161/Makefile.aut#L92-L98

Diffoscope:

![image](https://github.com/user-attachments/assets/c764d0b6-587a-4759-990e-9922647c88f1)

I temporarily patched it to remove timestamp generation https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/22374, I don't think manpages need them.

**Comment by gwsw** [comment]
I think this is the same issue as #567. That was fixed in c02f7554a1e5685e4332fb6857e95761953c8db4. But that fix doesn't remove timestamps from the man pages. It seems to me that most man pages do have timestamps. On my Fedora system I looked at 1277 man pages, and 987of them have a timestamp in the last line. It doesn't seem like a good idea for less's man page to be different from most of the others in this respect. But perhaps that timestamp could be changed to be baed on SOURCE_DATE_EPOCH as well.

**Comment by bbhtt** [comment]
The fix is not on master so I didn't notice it but yea using that for man pages too is probably also fine.

**Comment by avih** [comment]
> On my Fedora system I looked at 1277 man pages, and 987of them have a timestamp in the last line. It doesn't seem like a good idea for less's man page to be different from most of the others in this respect.

Agreed, but someone which needs a reproducible build have other priorities.

> But perhaps that timestamp could be changed to be baed on SOURCE_DATE_EPOCH as well.

Yeah, sounds good to me too.

**Comment by bbhtt** [comment]
Any idea if these fixes will go in master or later in release tags? I can't tell if the pos659 branch has a special significance.

**Comment by gwsw** [comment]
post659 was a development branch while the 668 bug fix release was being developed in master. Now that 668 is released, post659 will be merged back into master, probably in a week or so.

**Comment by gwsw** [comment]
Fixed in 98d5fd4ce14dd69ab092baa9372f85b8be187741.
