### ISSUE TITLE
Command not available for |, !, #, :e, etc

### ISSUE THREAD

**Issue by name-snrl** [gwsw/less#586]
Hello. I'm on NixOS and updated my system last night. `less` was updated from 661 to 668. The pipe stopped working with the message:

```
Command not available
```

**Comment by gwsw** [comment]
This sounds like the same issue as #584. The problem is not due to any change in less itself, but a change in the way NixOS builds it. Apparently they recently changed their build system to pass a --without-secure option to configure, which is not supported by any less version before less-669. To workaround this issue, you can just rebuild less-668 without using the --without-secure flag.

**Comment by name-snrl** [comment]
> build system to pass a --without-secure

Yes, you are right. Apologies and thanks for the reply and your time. There was a refactoring in the NixOS build script that enabled this flag by mistake
