### ISSUE TITLE
Allow ESC-e to invoke the sequence "g|$$EDITOR -"

### ISSUE THREAD

**Issue by rfagen** [gwsw/less#66]
While wandering the internet, I saw [an interesting workaround to being able to edit STDIN while using less](https://unix.stackexchange.com/questions/23304/piping-into-less-and-editing-cannot-edit-standard-input-error-workarounds/43460#43460).

I would like to propose adding an ESC-e command (which doesn't appear to be in use as of version 458) to stuff the keyboard with the sequence: `g|$$EDITOR -`

Or, maybe even: `g|$${VISUAL:-$EDITOR} -` which I'm amazed I was able to get correct the first time I typed it...

**Comment by gwsw** [comment]
This would work only when the editor supports editing stdin, and uses the "-" syntax to do it. Since this is not universal (for example, my version of emacs does not support it), it's probably not appropriate for a general release. However you can get the same effect by putting this line in your lesskey file:
`
\ee goto-line |$${VISUAL:-$EDITOR} -\n
`

**Comment by rfagen** [comment]
Ah! Cool. TIL -- there's a lesskey file

Thank you, by the way for so much `less` :)
