### ISSUE TITLE
Remember position in file ?

### ISSUE THREAD

**Issue by TheBrainScrambler** [gwsw/less#95]
Hello, I would like to know if it would be possible to add such feature ?
When you exit and reopen a file, it will jump again to the beginning. It would be nice to have either a keybind or a command to save current position, so that when you exit and reopen the file, less directly goes to the previous position. Or having some bookmark system, but this might complicate everything.

**Comment by gwsw** [comment]
This can be done by using the --save-marks option.

**Comment by TheBrainScrambler** [comment]
Indeed, thank you !

**Comment by jb55** [comment]
lastmark is not saved, is this intentional?

**Comment by gwsw** [comment]
I had assumed that lastmark is not very useful to save between sessions, because it is associated with the last movement command, and the last movement is less likely to be meaningful or even remembered when a new session is started. I'm open to hearing other views. An argument to the contrary is that it's an easy change and probably doesn't really impact users who don't expect it to be saved.

**Comment by jb55** [comment]
gwsw <notifications@github.com> writes:
> I had assumed that lastmark is not very useful to save between
> sessions, because it is associated with the last movement command, and
> the last movement is less likely to be meaningful or even remembered
> when a new session is started. I'm open to hearing other views. An
> argument to the contrary is that it's an easy change and probably
> doesn't really impact users who don't expect it to be saved.

I currently use a wrapper script for per-file histfiles:

https://jb55.com/s/ccfecd0ec73a0b71.txt

I current have less patched to support saved lastmarks and it works
well:

https://jb55.com/s/d6a1ae8045a3330f.txt

Whenever I open a file I've opened before with this script, I just type
'' to jump to the last position that I was at. Previously I had to
manually save a user mark, which I sometimes forgot to do.

**Comment by gwsw** [comment]
Added in a094f6fa036b3e856f9a4301e7f10d5159285ff8.

**Comment by GWHAYWOOD** [comment]
In my Bash login scripts I have the following:

alias li='less -S --save-marks --rscroll=- '

Because I'm *really* lazy, instead of typing 'less file' in full I almost always type 'li file'.

I'm generally viewing a single file, /var/log/mail.debug, which is a mail server log rotated monthly.  Depending on the time of the month and what I'm doing with milters it can be anything up to two gigabytes in size.

I use marks a lot.  Usually there will be between one and half a dozen marks for the file.  If I view a different file (for example /var/log/mail.debug.1) and then view /var/log/mail.debug the marks are still there for /var/log/mail.debug.  If, while I'm viewing /var/log/mail.debug.1, I give to 'less' the command to move to a mark in /var/log/mail.debug, it opens the file and jumps there.

Because of the --save-marks option, normally the marks I set are saved from one pager session to the next, so if I shut down less and start it up again I can use the marks I set in the previous session.

They are saved, that is, *UNLESS* for some reason I type 'less file' instead of 'li file'.

In that case the marks are all lost.

Is there a way to preserve them anyway?  I'd rather not alias 'less' to 'less --save-marks' if I don't have to.

Then, I suppose, I'd need a way to delete them all on purpose. :)

**Comment by gwsw** [comment]
@GWHAYWOOD perhaps something like this?

```function li { if [ -r ~/.lesshst.bak ]; then cp ~/.lesshst.bak ~/.lesshst; fi; less --save-marks $*; cp ~/.lesshst ~/.lesshst.bak; }```

This saves a copy of the history file after less exits, and then restores the history file before running less the next time. If the history file is modified by running less outside the li function, it will be overwritten by the saved file the next time you run li. (Of course, make necessary changes if your history file is somewhere other than ~/.lesshst.)

**Comment by GWHAYWOOD** [comment]
I can live with that. :)

Thanks for taking the time!
